name: Build/Test commit and publish pre-release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ 'windows-latest', 'ubuntu-latest' ]

    steps:
    - uses: actions/checkout@v4

    - name: Install Dependencies (Linux only)
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt-get install g++ libraylib-dev

    - name: Build
      run: |
        if [ "${{ matrix.os }}" == "windows-latest" ]; then
          g++ main.cpp -Wall -lraylib -lopengl32 -lgdi32 -lwinmm -Os -s -I"./include" -L"./lib" -o abductix_win_x64.exe
        else
          g++ main.cpp -Wall -lraylib -Os -s -I"./include" -L"./lib" -o abductix_linux
        fi

    - name: Upload Binaries
      uses: actions/upload-artifact@v3
      with:
        name: abductix_binaries
        path: |
          abductix_win_x64.exe
          abductix_linux

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Delete Existing Alpha Tag
      run: |
        git tag -d alpha || true
        git push origin :refs/tags/alpha || true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create Release
      uses: actions/create-release@v1
      with:
        tag_name: alpha
        release_name: "Automated build (${{ github.sha }})"
        draft: false
        prerelease: true
        body: "This is an automated build with binaries for windows and linux built from the commit [${{ github.sha }}](https://github.com/${{ github.repository }}/commit/${{ github.sha }})"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Release Assets
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: abductix_win_x64.exe
        asset_name: abductix_win_x64.exe
        asset_content_type: application/octet-stream

    - name: Upload Linux Binary
      if: needs.build.outputs.linux_binary_exists == 'true'
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: abductix_linux
        asset_name: abductix_linux
        asset_content_type: application/octet-stream
