name: Build/Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build
      run: g++ main.cpp -Wall -lraylib -lopengl32 -lgdi32 -lwinmm -Os -s -I"./include" -L"./lib" -o abductix_win_x64.exe